name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  http: ^1.1.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  firebase_database: ^11.1.6
  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_analytics: ^11.3.5
  firebase_app_check: ^0.3.1+6
  flutter_plugin_android_lifecycle: ^2.0.23
  shared_preferences: ^2.3.3
  firebase_storage: ^12.3.6
  image_picker: ^1.1.2
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/img/
